"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { addDays, endOfDay, endOfMonth, endOfWeek, format, isWithinInterval, startOfDay, startOfMonth, startOfWeek } from "date-fns";
import { ptBR } from "date-fns/locale";
import { AlertTriangle, ChevronLeft, ChevronRight } from "lucide-react";
import { OrdemServico, TIPO_LABEL } from "@/lib/os";
type Visao = "dia" | "semana" | "mes";
export function AgendaOperacional({ ordens, tecnico }: { ordens: OrdemServico[]; tecnico: boolean }) {
  const [visao, setVisao] = useState<Visao>("semana"); const [referencia, setReferencia] = useState(() => new Date());
  const intervalo = useMemo(() => visao === "dia" ? { start: startOfDay(referencia), end: endOfDay(referencia) } : visao === "semana" ? { start: startOfWeek(referencia, { weekStartsOn: 1 }), end: endOfWeek(referencia, { weekStartsOn: 1 }) } : { start: startOfMonth(referencia), end: endOfMonth(referencia) }, [referencia, visao]);
  const itens = ordens.filter((o) => o.data_hora_agendada && isWithinInterval(new Date(o.data_hora_agendada), intervalo)); const conflitos = new Set<string>();
  itens.forEach((a, i) => itens.slice(i + 1).forEach((b) => { if (a.tecnico_id && a.tecnico_id === b.tecnico_id && Math.abs(+new Date(a.data_hora_agendada!) - +new Date(b.data_hora_agendada!)) < 90 * 60 * 1000) { conflitos.add(a.id); conflitos.add(b.id); } }));
  const dias: Date[] = []; for (let d = intervalo.start; d <= intervalo.end; d = addDays(d, 1)) dias.push(d);
  function mover(valor: number) { setReferencia((atual) => addDays(atual, valor * (visao === "dia" ? 1 : visao === "semana" ? 7 : 30))); }
  return <div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-base-border bg-white p-3"><div className="flex gap-1">{(["dia", "semana", "mes"] as Visao[]).map((v) => <button key={v} type="button" onClick={() => setVisao(v)} className={visao === v ? "btn-primary" : "btn-secondary"}>{v[0].toUpperCase() + v.slice(1)}</button>)}</div><div className="flex items-center gap-2"><button type="button" aria-label="Período anterior" className="btn-secondary px-3" onClick={() => mover(-1)}><ChevronLeft size={16}/></button><button type="button" className="btn-secondary" onClick={() => setReferencia(new Date())}>Hoje</button><button type="button" aria-label="Próximo período" className="btn-secondary px-3" onClick={() => mover(1)}><ChevronRight size={16}/></button></div></div>
    <p className="mt-4 text-sm font-bold capitalize">{format(intervalo.start, "dd MMM", { locale: ptBR })} — {format(intervalo.end, "dd MMM yyyy", { locale: ptBR })}</p>{conflitos.size > 0 && <p className="mt-3 flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700"><AlertTriangle size={16}/>Há {conflitos.size} serviços com possível conflito de horário para o mesmo técnico.</p>}
    <div className={`mt-4 grid gap-3 ${visao === "mes" ? "sm:grid-cols-2 xl:grid-cols-4" : "xl:grid-cols-2"}`}>{dias.map((dia) => { const doDia = itens.filter((o) => new Date(o.data_hora_agendada!).toDateString() === dia.toDateString()).sort((a,b) => +new Date(a.data_hora_agendada!) - +new Date(b.data_hora_agendada!)); return <section key={dia.toISOString()} className="min-h-28 rounded-xl border border-base-border bg-white p-4"><h2 className="text-xs font-bold capitalize text-ink-muted">{format(dia, "EEEE, dd/MM", { locale: ptBR })}</h2><div className="mt-3 space-y-2">{doDia.map((o) => <Link href={`/os/${o.id}`} key={o.id} className={`block rounded-lg border p-3 text-xs ${conflitos.has(o.id) ? "border-red-300 bg-red-50" : "border-base-border hover:border-amber"}`}><b>{format(new Date(o.data_hora_agendada!), "HH:mm")} · {o.cliente_nome}</b><span className="mt-1 block truncate text-ink-muted">{TIPO_LABEL[o.tipo]} · {o.veiculo_identificador}</span>{!tecnico && <span className="mt-1 block font-medium">{o.tecnico?.nome ?? "Sem técnico"}</span>}</Link>)}{doDia.length === 0 && <p className="text-[11px] text-ink-faint">Sem serviços</p>}</div></section>; })}</div></div>;
}
