"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {addDays,endOfDay,endOfMonth,endOfWeek,format,isWithinInterval,startOfDay,startOfMonth,startOfWeek} from "date-fns";
import {ptBR} from "date-fns/locale";
import {AlertTriangle,ChevronLeft,ChevronRight,Search} from "lucide-react";
import {OrdemServico,STATUS_LABEL,TIPO_LABEL} from "@/lib/os";
type Visao="dia"|"semana"|"mes";
export function AgendaOperacional({ordens,tecnico}:{ordens:OrdemServico[];tecnico:boolean}){
  const[visao,setVisao]=useState<Visao>("semana"),[referencia,setReferencia]=useState(()=>new Date()),[busca,setBusca]=useState(""),[status,setStatus]=useState("");
  const intervalo=useMemo(()=>visao==="dia"?{start:startOfDay(referencia),end:endOfDay(referencia)}:visao==="semana"?{start:startOfWeek(referencia,{weekStartsOn:1}),end:endOfWeek(referencia,{weekStartsOn:1})}:{start:startOfMonth(referencia),end:endOfMonth(referencia)},[referencia,visao]);
  const termo=busca.trim().toLocaleLowerCase("pt-BR"),filtradas=ordens.filter(os=>(!status||os.status===status)&&(!termo||[os.cliente_nome,os.veiculo_identificador,os.veiculo_modelo,os.local].some(valor=>valor?.toLocaleLowerCase("pt-BR").includes(termo)))),itens=filtradas.filter(os=>os.data_hora_agendada&&isWithinInterval(new Date(os.data_hora_agendada),intervalo)),conflitos=new Set<string>();
  itens.forEach((a,i)=>itens.slice(i+1).forEach(b=>{if(a.tecnico_id&&a.tecnico_id===b.tecnico_id&&Math.abs(+new Date(a.data_hora_agendada!)-+new Date(b.data_hora_agendada!))<90*60*1000){conflitos.add(a.id);conflitos.add(b.id)}})); const dias:Date[]=[];for(let dia=intervalo.start;dia<=intervalo.end;dia=addDays(dia,1))dias.push(dia);function mover(valor:number){setReferencia(atual=>addDays(atual,valor*(visao==="dia"?1:visao==="semana"?7:30)))}
  return <div><div className="mt-6 grid gap-2 rounded-xl border border-base-border bg-white p-3 sm:grid-cols-[1fr_190px]"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-faint"/><input value={busca} onChange={e=>setBusca(e.target.value)} className="campo pl-9" placeholder="Buscar nome, placa, chassi ou modelo"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="campo"><option value="">Todos os status</option>{Object.entries(STATUS_LABEL).filter(([id])=>!["atrasado","critico","concluido"].includes(id)).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div>
    {termo?<ResultadosBusca ordens={filtradas} tecnico={tecnico}/>:<><div className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-base-border bg-white p-3"><div className="flex gap-1">{(["dia","semana","mes"] as Visao[]).map(item=><button key={item} type="button" onClick={()=>setVisao(item)} className={visao===item?"btn-primary":"btn-secondary"}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div><div className="flex items-center gap-2"><button type="button" aria-label="Período anterior" className="btn-secondary px-3" onClick={()=>mover(-1)}><ChevronLeft size={16}/></button><button type="button" className="btn-secondary" onClick={()=>setReferencia(new Date())}>Hoje</button><button type="button" aria-label="Próximo período" className="btn-secondary px-3" onClick={()=>mover(1)}><ChevronRight size={16}/></button></div></div><p className="mt-4 text-sm font-bold capitalize">{format(intervalo.start,"dd MMM",{locale:ptBR})} — {format(intervalo.end,"dd MMM yyyy",{locale:ptBR})}</p>{conflitos.size>0&&<p className="mt-3 flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700"><AlertTriangle size={16}/>Há {conflitos.size} serviços com possível conflito de horário para o mesmo técnico.</p>}<div className={`mt-4 grid gap-3 ${visao==="mes"?"sm:grid-cols-2 xl:grid-cols-4":"xl:grid-cols-2"}`}>{dias.map(dia=>{const doDia=itens.filter(os=>new Date(os.data_hora_agendada!).toDateString()===dia.toDateString()).sort((a,b)=>+new Date(a.data_hora_agendada!)-+new Date(b.data_hora_agendada!));return <section key={dia.toISOString()} className="min-h-28 rounded-xl border border-base-border bg-white p-4"><h2 className="text-xs font-bold capitalize text-ink-muted">{format(dia,"EEEE, dd/MM",{locale:ptBR})}</h2><div className="mt-3 space-y-2">{doDia.map(os=><ItemAgenda key={os.id} os={os} tecnico={tecnico} conflito={conflitos.has(os.id)}/>)}{doDia.length===0&&<p className="text-[11px] text-ink-faint">Sem serviços</p>}</div></section>})}</div></>}
  </div>
}
function ResultadosBusca({ordens,tecnico}:{ordens:OrdemServico[];tecnico:boolean}){const lista=[...ordens].sort((a,b)=>+new Date(b.data_hora_agendada!)-+new Date(a.data_hora_agendada!));return <section className="mt-4 rounded-xl border border-base-border bg-white p-4"><h2 className="font-bold">Resultados da busca ({lista.length})</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{lista.map(os=><ItemAgenda key={os.id} os={os} tecnico={tecnico} conflito={false}/>)}{lista.length===0&&<p className="text-xs text-ink-faint">Nenhuma OS encontrada.</p>}</div></section>}
function ItemAgenda({os,tecnico,conflito}:{os:OrdemServico;tecnico:boolean;conflito:boolean}){return <Link href={`/os/${os.id}`} className={`block rounded-lg border p-3 text-xs ${conflito?"border-red-300 bg-red-50":"border-base-border hover:border-amber"}`}><b>{os.data_hora_agendada?format(new Date(os.data_hora_agendada),"dd/MM/yyyy HH:mm"):"Sem data"} · {os.cliente_nome}</b><span className="mt-1 block truncate text-ink-muted">{TIPO_LABEL[os.tipo]} · {os.veiculo_modelo} · {os.veiculo_identificador}</span><span className="mt-1 block text-ink-muted">{STATUS_LABEL[os.status]??os.status}</span>{!tecnico&&<span className="mt-1 block font-medium">{os.tecnico?.nome??"Sem técnico"}</span>}</Link>}
